upstream frontend {
    server  frontend:8080;
}

upstream backend {
    server  backend:5000;
}

upstream titiler {
    server  titiler:8888;
}

server {
    listen 80;
    server_name localhost;

    location / {
        proxy_set_header Host $host;

        proxy_pass http://frontend;
    }

    location /api {
        # forward incoming requests to FastAPI backend container
        proxy_pass  http://backend;

        # disable request and response buffering
        proxy_request_buffering off;
        proxy_buffering         off;
        proxy_http_version      1.1;

        # add X-Forwarded-* headers
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /cog {
        # Proxy valid requests to the backend
        proxy_set_header Host $host;

        proxy_pass http://titiler;
    }

    location /static {
        proxy_set_header Host $host;

        proxy_pass http://backend;
    }
}